/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-chip-input.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {AnypointChipInput} from './src/AnypointChipInput.js';

export {AnypointChipInput};
